### ISSUE TITLE
How to Ignore errors to proceed with Automation 

### ISSUE THREAD

**Issue by kviji** [taphos/unity-uitest#1]
Hi, 

I am testing Hololens applications that are developed within Unity and trying to perform simple Automation tests within Unity using your framework.
Currently , there is a small error when I play the project, however, it does not affect from playing around with the application. I have created a UI test , but the tests do not proceed because of the error.
Is there a way to ignore the error and proceed with Automation?

**Comment by taphos** [comment]
Hi,
You could ignore the error inside the error callback 
`Application.LogCallback logReceived`
In TestRunner or ReportingTestRunner (depending of which one you are using)
Same as done for Unity internal errors check out method UnityInternalError()
