### ISSUE TITLE
Press unsuccessful

### ISSUE THREAD

**Issue by kviji** [taphos/unity-uitest#2]
Hi,

I want to click a Game object which has no button component associated with it but the on click is handled through code itself. 
When tried to do so, I am getting the following error.
GameObject Toggle_Search [UnityEngine.GameObject] does not have a button component attached.

Any ideas how to resolve this?

**Comment by taphos** [comment]
Hi,
If you are using custom button solution, change the code which simulates the button click in UITest.cs. Its the ButtonAccessible subclass GetAccessibilityMessage method.

**Comment by kviji** [comment]
Hi ,

That worked! Thanks a lot.
Any idea if we can iterate through a list of game objects with the same name and fetch the text inside it?

**Comment by taphos** [comment]
You would have to implement that by yourself, Unity's GameObject.Find returns only the first object it finds. I would recursively go though all the Transforms, checking names manually.

**Comment by kviji** [comment]
Got it. Thanks
