### ISSUE TITLE
examples of integrating it with jenkins or other building

### ISSUE THREAD

**Issue by jaroslaw-weber** [taphos/unity-uitest#4]
is it possible to integrate this script with jenkins?
if yes, it would be nice to have tutorial about it.

**Comment by taphos** [comment]
It is possible to execute tests from command-line using Unity batch mode. Just make jenkins run Unity with specific arguments:
`
./Unity -batchmode -projectPath <path>  -runTests -testPlatform playmode
`
Check Unity manual https://docs.unity3d.com/Manual/CommandLineArguments.html
